# Generated by Django 4.1.7 on 2023-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_summodel_sums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summodel',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
