# Generated by Django 4.1.7 on 2023-03-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_region_hotelnumber_category_hotelnumber_how_many_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AddField(
            model_name='hotelnumber',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выезда'),
        ),
        migrations.AddField(
            model_name='hotelnumber',
            name='date_started',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.region', verbose_name='Регион'),
        ),
    ]
