# Generated by Django 4.1.7 on 2023-03-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_region_options_hotelnumber_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelnumber',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер'),
        ),
    ]
