# Generated by Django 4.1.7 on 2023-03-15 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_hotelnumber_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата на которую надо формировать отчет')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.hotel', verbose_name='Отель')),
            ],
        ),
        migrations.RemoveField(
            model_name='hotelnumber',
            name='level',
        ),
        migrations.CreateModel(
            name='RoomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Стандарт', 'Стандарт'), ('Люкс', 'Люкс'), ('Апартамент', 'Апартамент')], default='Стандарт', max_length=100, verbose_name='Категория')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='application.report')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.status', verbose_name='Статус')),
            ],
        ),
    ]
