# Generated by Django 4.1.7 on 2023-03-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_report_remove_hotelnumber_level_roomreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AlterModelOptions(
            name='roomreport',
            options={'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
    ]
