# Generated by Django 4.1.7 on 2023-03-14 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0006_alter_status_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('date_len', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сколько ночей')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.hotelnumber', verbose_name='Номер отеля')),
            ],
        ),
    ]
