# Generated by Django 4.1.7 on 2023-03-15 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_status_text'),
        ('booking', '0002_alter_booking_options_alter_booking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.hotel', verbose_name='Отель'),
        ),
    ]
