# Generated by Django 4.1.7 on 2023-03-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=150, verbose_name='Плательщик')),
                ('type_of_payer', models.CharField(choices=[('Физ. лицо', 'Физ. лицо'), ('Юр. лицо', 'Юр. лицо')], max_length=50, verbose_name='Вид плательщика')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=150, verbose_name='ФИО')),
                ('tel', models.CharField(max_length=11, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32, verbose_name='Стоимость'),
        ),
    ]
