# Generated by Django 4.1.7 on 2023-03-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_clients_booking_payer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='clients',
        ),
        migrations.AddField(
            model_name='client',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='booking.booking'),
        ),
    ]
