# Generated by Django 4.1.7 on 2023-03-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_booking_clients_client_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Плательщик', 'verbose_name_plural': 'Плательщики'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='book',
        ),
        migrations.AddField(
            model_name='booking',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Бронь подтверждена'),
        ),
        migrations.AddField(
            model_name='guest',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='booking.booking'),
        ),
    ]
