# Generated by Django 4.1.7 on 2023-03-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
    ]
