# Generated by Django 4.1.7 on 2023-03-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='tel',
            field=models.CharField(max_length=100, verbose_name='Телефон'),
        ),
    ]
