# Generated by Django 4.1.7 on 2023-03-14 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_alter_booking_options_alter_booking_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата заезда')),
                ('client', models.CharField(max_length=50, verbose_name='ИМЯ заезжающего')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking', unique=True, verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Заезд',
                'verbose_name_plural': 'Заезды',
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата выезда')),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkInOut.checkin', unique=True, verbose_name='Заезд')),
            ],
            options={
                'verbose_name': 'Выезд',
                'verbose_name_plural': 'Выезды',
            },
        ),
    ]
