# Generated by Django 4.1.7 on 2023-03-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_guest_tel'),
        ('checkInOut', '0002_aemptymodel_emptymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AEmptyModel',
        ),
        migrations.CreateModel(
            name='TodayLogoutNumbers',
            fields=[
            ],
            options={
                'verbose_name': 'Номера для выезда сегодня',
                'verbose_name_plural': 'Номера для выезда сегодня',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('booking.booking',),
        ),
        migrations.CreateModel(
            name='TodayNumbers',
            fields=[
            ],
            options={
                'verbose_name': 'Номера для заезда сегодня',
                'verbose_name_plural': 'Номера для заезда сегодня',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('booking.booking',),
        ),
    ]
