# Generated by Django 4.1.7 on 2023-03-15 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_report_options_alter_roomreport_options'),
        ('booking', '0013_alter_guest_tel'),
        ('checkInOut', '0003_delete_aemptymodel_todaylogoutnumbers_todaynumbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emptymodel',
            options={'verbose_name': 'Рабочий стол', 'verbose_name_plural': 'Рабочий стол'},
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='client',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='date',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='checkin',
        ),
        migrations.AddField(
            model_name='checkin',
            name='date_end',
            field=models.DateField(null=True, verbose_name='Дата выезда'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='date_start',
            field=models.DateField(null=True, verbose_name='Дата заезда'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.hotel', verbose_name='Отель'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.hotelnumber', verbose_name='Номер в отеле (комната)'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.hotel', verbose_name='Отель'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.hotelnumber', verbose_name='Освобождаемый номер'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking', unique=True, verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата выезда'),
        ),
        migrations.CreateModel(
            name='CheckGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkInOut.checkin')),
                ('checkOut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkInOut.checkout')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.guest', verbose_name='Гость')),
            ],
            options={
                'verbose_name': 'Заезжающий гость',
                'verbose_name_plural': 'Заезжающие гости',
            },
        ),
    ]
